services:
  - type: web
    name: face-recognition-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
      - key: RENDER
        value: true
    secrets:
      - name: firebase-credentials  # Remove .json extension
        mountPath: /etc/secrets/firebase-credentials  # Remove .json extension